### ISSUE TITLE
Library - Automated CI/CD to upload latest commits to npm

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-frontend-lib#4]

**Comment by JohnnyCrazy** [comment]
This is now automated in the following way:

Since we're in a library, where it is important to differentiate between breaking and incremental changes, I thought we could use [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/). With this commit message style, you have to automatically specify what kind of change you're introducing. 

* Is it an incremental feature for the react router? `feat(react-router): added xy`
* Is it just some docs/chore work, which has no impact on release? `chore(release): fixed release script`
* Is it a refactoring which breaks old stuff? 

```
refactor!: reorganized all exports

BREAKING CHANGE: Instead of importing like this: ``, it now has to be done like that: ``
```

Everytime there is a new commit on master, the actions workflow checks if a new release is necessary. This also means we don't have to think about when something is gonna be released, because everything in master is automatically released. If we want to group stuff together, we can always merge stuff into a temporary branch and merge it into master later.
